### ISSUE TITLE
Match filename case to class name case for Composer autoloader

### ISSUE THREAD

**Issue by mcki0127** [uguranyum/yii2-icalender#1]
see [https://forum.yiiframework.com/t/class-in-vendor-not-found/127172/4](https://forum.yiiframework.com/t/class-in-vendor-not-found/127172/4) 
> Please rename the file vendor/uguranyum/icalender/icalender.php to vendor/uguranyum/icalender/iCalender.php (camelcase, lower “i” upper “C”)

**Comment by demonking** [comment]
@mcki0127  it's merged, you can close this issue ;)
https://github.com/uguranium/yii2-icalender/pull/2
